version: "3"

services:
  tests:
    build: .
    volumes:
      - /usr/app
    ports:
      - "3333:3333"
    links:
      - selenium-hub

  selenium-hub:
    image: selenium/hub:3.141.59-uranium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-uranium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  # firefox:
  #   image: selenium/node-firefox:3.141.59-uranium
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444